Main_app/urls.py
from django.urls import path

from . import views

app_name = 'Main_app'

urlpatterns = [
    path('',views.index, name='index'),
    path('topics',views.topics,name='topics'),
    path('topics/<int:topic_id>/',views.topic,name='topic'),
    path('new_topic',views.new_topic,name='new_topic'),
    path('new_entry/<int:topic_id>/',views.new_entry,name='new_entry'),
    path('edit_entry/<int:entry_id>/',views.edit_entry,name='edit_entry'),



]

#<a href="{% url 'Main_app"


''' the process goes urls.py > views.py > templates.html '''

#Mattisdumb123 is password

learning_log/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('Main_app.urls')),
    path('users/',include('users.urls')),
]

users/urls.py
from django.urls import path,include

app_name = 'users'

urlpatterns = [
    path('',include('django.contrib.auth.urls'))
]

Main_app/models.py
from django.db import models

# Create your models here.





#make a change here, then do python manage.py makemigrations, then python manage.py migrate, update the admin.py
class Topic(models.Model):
    text = models.CharField(max_length=200)

    data_added = models.DateTimeField(auto_now_add=True)


    def __str__(self):
        return self.text


class Entry(models.Model):
    topic = models.ForeignKey(Topic, on_delete=models.CASCADE)
    text = models.TextField()
    data_added = models.DateTimeField(auto_now_add=True)


    class Meta:
        verbose_name_plural = 'Entries'
        
    def __str__(self):
        return f"{self.text[:50]}..."

users/models.py
from django.db import models

# Create your models here.

Main_app/forms.py
from django import forms

from .models import * 

class TopicForm(forms.ModelForm):
    class Meta:
        model = Topic
        fields = ['text']
        labels = {'text':'Topic Name'}

class EntryForm(forms.ModelForm):
    class Meta:
        model = Entry
        fields = ['text']
        labels = {'text':''}

        widgets = {'text': forms.Textarea(attrs={'cols':80})}
        

Main_app/views.py
from django.shortcuts import render, redirect
from .models import *
from .forms import *
# Create your views here.

def index(request):
    """The Home page for learning log"""
    return render(request, 'Main_app/index.html')


def topics(request):
    topics = Topic.objects.order_by('-data_added')

    context = {'t':topics}

    return render(request, 'Main_app/topics.html',context)
    '''the key t is the variable you will use on the html page '''
    ''' the value is the variable you are using in the view'''

def topic(request,topic_id):
    t = Topic.objects.get(id=topic_id)
    entries = Entry.objects.filter(topic=t)

    context = {'topic':t, 'entries':entries}

    return render(request, 'Main_app/topic.html',context)

''' A get request is getting data from the database'''
''' A post request is asking to write something to the database'''

def new_topic(request):
    if request.method != 'POST':
        form = TopicForm()
    else:
        print(request.POST)
        form = TopicForm(data=request.POST)
        if form.is_valid():
            form.save()
            return redirect('Main_app:topics')

    context = {'form':form}
    return render(request, 'Main_app/new_topic.html',context)


def new_entry(request, topic_id):
    topic = Topic.objects.get(id=topic_id)
    if request.method != 'POST':
        form = EntryForm()
    else:
        print(request.POST)
        form = EntryForm(data=request.POST)
        if form.is_valid():
            new_entry = form.save(commit=False)
            new_entry.topic = topic
            new_entry.save()
            return redirect('Main_app:topic', topic_id=topic_id)

    context = {'form':form,'topic':topic}
    return render(request, 'Main_app/new_entry.html',context)


def edit_entry(request, entry_id):
    entry = Entry.objects.get(id=entry_id) # use this variable to reference the model
    topic = entry.topic #same variable

    if request.method != 'POST':
        form = EntryForm(instance=entry) 
    else:
        form = EntryForm(instance=entry,data=request.POST) 
        if form.is_valid():
            form.save()
            return redirect('Main_app:topic', topic_id=topic.id) 
            # topic_id is a variable name / topic.idd is an attribute

    context = {'form':form,'topic':topic, 'entry':entry}
    return render(request, 'Main_app/edit_entry.html',context)

    



            

users/views.py
from django.shortcuts import render

# Create your views here.

Main_app/templates/main_app/base.html
<p>
    <a href="{% url 'Main_app:index' %}">Learning Log</a>
    
    
    {% if user.is_authenticated %} 
    Hello, {{ user.username }}
    <a href="{% url 'Main_app:topics' %}">Topics</a>
    <a href="{% url 'users:logout' %}">Log Out</a>
    {% else %} 
    <a href="{% url 'users:login' %}">Log In</a>
    {% endif %}




</p>

{% block content %}

{% endblock content %}

Main_app/templates/main_app/edit_entry.html
{% extends "Main_app/base.html" %}

{% block content %}

<p><a href="{% url 'Main_app:topic' topic.id %}">{{topic}}</a></p>

<p>Edit Entry</p>



<form action="{% url 'Main_app:edit_entry' entry.id %}" method="post">

    {% csrf_token %} 

    {{ form.as_p }}

    <button name="Submit">Save changes</button>

    
</form>


{% endblock content %}

Main_app/templates/main_app/index.html
{% extends "Main_app/base.html" %} 

{% block content %} 

<p>
    Learning logs helps you keep track of your learning, for any topic you
    are learning about.
</p>

{% endblock content %} 

Main_app/templates/main_app/new_entry.html
{% extends "Main_app/base.html" %}

{% block content %}

<p><a href="{% url 'Main_app:topic' topic.id %}">{{topic}}</a></p>

<p>Add a New Entry</p>



<form action="{% url 'Main_app:new_entry' topic.id %}" method="post">

    {% csrf_token %} 

    {{ form.as_p }}

    <button name="Submit">Add entry</button>

    
</form>


{% endblock content %}

Main_app/templates/main_app/new_topic.html
{% extends "Main_app/base.html" %}

{% block content %}

<p>Add a New Topic</p>

<form action="{% url 'Main_app:new_topic' %}" method="post">

    {% csrf_token %} 

    {{ form.as_p }}

    <button name="Submit">Add topic</button>

    
</form>


{% endblock content %}

Main_app/templates/main_app/topic.html
{% extends "Main_app/base.html" %}

{% block content %}

<p>Topic: {{ topic }}</p>

<ul>

    {% for e in entries %}
    <li>{{ e.text }}</li>
    --{{ e.data_added }}
    <p>
        <a href="{% url 'Main_app:edit_entry' e.id %}">edit entry</a>
    </p>
    {% empty %}
    <li>No entries for this topic have been added yet</li>
    {% endfor %}
</ul>

<p>
    <a href="{% url 'Main_app:new_entry' topic.id %}">Addd a new entry</a>
</p>


{% endblock content %}

Main_app/templates/main_app/topics.html
{% extends "Main_app/base.html" %}

{% block content %}

<p>Topics</p>

<ul>

    {% for topic in t %}
    <li>
        <a href="{% url 'Main_app:topic' topic.id %}"> {{topic.text}}</a>
        </li>

    {% empty %}
    <li>No topic has been added yet</li>
    {% endfor %}
</ul>

<a href="{% url 'Main_app:new_topic' %}">Add a new topic</a>



{% endblock content %}